// <auto-generated />
using System;
using ActivityCenter.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ActivityCenter.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20190919033849_rsvp1")]
    partial class rsvp1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ActivityCenter.Models.ActivityModel", b =>
                {
                    b.Property<int>("Activity_Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Coordinator_Id");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000);

                    b.Property<double>("Duration1");

                    b.Property<string>("DurationMeasure")
                        .IsRequired();

                    b.Property<DateTime>("EndDateTime");

                    b.Property<DateTime>("StartDateTime");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(25);

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Activity_Id");

                    b.HasIndex("Coordinator_Id");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("ActivityCenter.Models.UserModel", b =>
                {
                    b.Property<int>("User_Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<string>("Password")
                        .IsRequired();

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("User_Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ActivityCenter.RSVPModel", b =>
                {
                    b.Property<int>("RSVP_Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Activity_Id");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<int>("User_Id");

                    b.HasKey("RSVP_Id");

                    b.HasIndex("Activity_Id");

                    b.HasIndex("User_Id");

                    b.ToTable("RSVPs");
                });

            modelBuilder.Entity("ActivityCenter.Models.ActivityModel", b =>
                {
                    b.HasOne("ActivityCenter.Models.UserModel", "Coordinator")
                        .WithMany()
                        .HasForeignKey("Coordinator_Id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ActivityCenter.RSVPModel", b =>
                {
                    b.HasOne("ActivityCenter.Models.ActivityModel", "Activity")
                        .WithMany("RSVPed")
                        .HasForeignKey("Activity_Id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ActivityCenter.Models.UserModel", "User")
                        .WithMany()
                        .HasForeignKey("User_Id")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
